[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "iasid"
version = "0.3.0"
description = "Совершенно бесполезный набор утилит"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name = "vikakyni11-coder", email = "vikakyni11@gmail.com" }]

[project.scripts]
iasid = "iasid.cli:main"

[tool.setuptools.packages.find]
include = ["iasid*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
